codecov:
  max_report_age: off

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto

ignore:
  - "tests/"
  - "docs/"
  - "scripts/"
  - "examples/"
  - "**/__init__.py"
  - "**/version.py"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
