site_name: XX Shell Documentation
site_url: https://your-org.github.io/xx-aider/
repo_url: https://github.com/your-org/xx-aider

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.sections
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.emoji
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
  - Commands:
    - Overview: commands/index.md
    - Core Commands: commands/core.md
    - Plugin Commands: commands/plugins.md
  - Development:
    - Setup: development/setup.md
    - Testing: development/testing.md
    - Contributing: development/contributing.md
  - API Reference:
    - Core: api/core.md
    - Plugins: api/plugins.md
    - Session: api/session.md
