name: Deploy Documentation

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/deploy-docs.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mkdocs-git-revision-date-localized-plugin

      - name: Build and deploy
        uses: mhausenblas/mkdocs-deploy-gh-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config_file: mkdocs.yml
          deploy_branch: gh-pages
          extra_plugins: git-revision-date-localized
